/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package putrimarket.forn;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import putrimarket.koneksi.koneksi;

/**
 *
 * @author tobis
 */
public class Kasir extends javax.swing.JPanel {
    private DefaultTableModel tableModel;
    private Connection conn = new koneksi().connect();

    /**
     * Creates new form Kasir
     */
    public Kasir() {
        initComponents();
        loadDataTable();
    }
    
    private void loadDataTable() {
        String sql = "SELECT * FROM kasir";
        try (PreparedStatement ps = conn.prepareStatement(sql);
             ResultSet rs = ps.executeQuery()) {
            tableModel = (DefaultTableModel) table.getModel();
            tableModel.setRowCount(0);
            while (rs.next()) {
                tableModel.addRow(new Object[]{
                    rs.getString("id_kasir"),
                    rs.getString("nama_kasir"),
                    rs.getString("no_telp"),
                    rs.getString("alamat")
                });
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                "Terjadi Kesalahan Saat Memuat Data Kasir!\n" + e.getMessage(),
                "Error",
                JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        inputIdKasir = new javax.swing.JTextField();
        inputNamaKasir = new javax.swing.JTextField();
        inputNoTelpKasir = new javax.swing.JTextField();
        inputAlamatKasir = new javax.swing.JTextField();
        saveBtn = new javax.swing.JButton();
        ubahBtn = new javax.swing.JButton();
        hapusBtn = new javax.swing.JButton();
        ulangBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        inputCariKasir = new javax.swing.JTextField();
        cariBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 51));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Kasir");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jLabel1)
                .addContainerGap(53, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setText("ID Kasir");

        jLabel3.setText("Nama Kasir");

        jLabel5.setText("No Telepon");

        jLabel6.setText("Alamat");

        saveBtn.setText("Simpan");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        ubahBtn.setText("Ubah");
        ubahBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ubahBtnActionPerformed(evt);
            }
        });

        hapusBtn.setText("Hapus");
        hapusBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusBtnActionPerformed(evt);
            }
        });

        ulangBtn.setText("Ulang");
        ulangBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ulangBtnActionPerformed(evt);
            }
        });

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Nama", "No Telp", "Alamat"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(table);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Navigasi");

        jLabel8.setText("1. Tombol \"Simpan\" untuk menyimpan data");

        jLabel9.setText("2. Tombol \"Ubah\" untuk mengubah data");

        jLabel10.setText("3. Tombol \"Hapus\" untuk menghapus data");

        jLabel11.setText("4. Tombol \"Ulang\" untuk mengulang input data");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel8))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9)
                            .addComponent(jLabel11))))
                .addContainerGap(90, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        cariBtn.setText("Cari");
        cariBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cariBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 770, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addGap(68, 68, 68)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(inputIdKasir, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
                                    .addComponent(inputNamaKasir)
                                    .addComponent(inputNoTelpKasir)
                                    .addComponent(inputAlamatKasir))
                                .addGap(37, 37, 37)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(saveBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ubahBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(hapusBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ulangBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(inputCariKasir, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cariBtn))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(321, 321, 321)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(inputIdKasir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(inputNamaKasir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(inputNoTelpKasir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(inputAlamatKasir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveBtn)
                    .addComponent(ubahBtn)
                    .addComponent(hapusBtn)
                    .addComponent(ulangBtn)
                    .addComponent(inputCariKasir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cariBtn))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        if (inputIdKasir.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this,
                "Tidak Dapat Menyimpan Data. Kamu Belum Mengisi ID Kasir!",
                "Peringatan",
                JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (inputNamaKasir.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this,
                "Tidak Dapat Menyimpan Data. Kamu Belum Mengisi Nama Kasir!",
                "Peringatan",
                JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (inputNoTelpKasir.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this,
                "Tidak Dapat Menyimpan Data. Kamu Belum Mengisi No. Telp Kasir!",
                "Peringatan",
                JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (inputAlamatKasir.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this,
                "Tidak Dapat Menyimpan Data. Kamu Belum Mengisi Alamat Kasir!",
                "Peringatan",
                JOptionPane.WARNING_MESSAGE);
            return;
        }

        String sqlCheck = "SELECT * FROM kasir WHERE id_kasir=?";
        String sqlInsert = "INSERT INTO kasir (id_kasir, nama_kasir, no_telp, alamat) VALUES (?, ?, ?, ?)";

        try (PreparedStatement psCheck = conn.prepareStatement(sqlCheck)) {
            psCheck.setString(1, inputIdKasir.getText().toUpperCase());
            ResultSet rs = psCheck.executeQuery();

            if (rs.next()) {
                JOptionPane.showMessageDialog(this,
                    "Data Kasir Dengan ID : " + inputIdKasir.getText().toUpperCase() + " Sudah Terdaftar!",
                    "Informasi",
                    JOptionPane.INFORMATION_MESSAGE);
            } else {
                try (PreparedStatement psInsert = conn.prepareStatement(sqlInsert)) {
                    psInsert.setString(1, inputIdKasir.getText().toUpperCase());
                    psInsert.setString(2, inputNamaKasir.getText());
                    psInsert.setString(3, inputNoTelpKasir.getText());
                    psInsert.setString(4, inputAlamatKasir.getText());

                    psInsert.executeUpdate();
                    loadDataTable();
                    JOptionPane.showMessageDialog(this,
                        "Data Kasir Dengan ID : " + inputIdKasir.getText().toUpperCase() + " Berhasil Disimpan!",
                        "Sukses",
                        JOptionPane.INFORMATION_MESSAGE);
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                "Terjadi Kesalahan Saat Menyimpan Data Kasir!\n" + e.getMessage(),
                "Error",
                JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }//GEN-LAST:event_saveBtnActionPerformed

    private void ubahBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ubahBtnActionPerformed
        if (inputIdKasir.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this,
                "Tidak Dapat Mengubah Data. Kamu Belum Mengisi ID Kasir!",
                "Peringatan",
                JOptionPane.WARNING_MESSAGE);
            return;
        }

        String sqlCheck = "SELECT * FROM kasir WHERE id_kasir=?";
        String sqlUpdate = "UPDATE kasir SET nama_kasir=?, no_telp=?, alamat=? WHERE id_kasir=?";

        try (PreparedStatement psCheck = conn.prepareStatement(sqlCheck)) {
            psCheck.setString(1, inputIdKasir.getText().toUpperCase());
            ResultSet rs = psCheck.executeQuery();

            if (rs.next()) {
                try (PreparedStatement psUpdate = conn.prepareStatement(sqlUpdate)) {
                    psUpdate.setString(1, inputNamaKasir.getText().isEmpty() ? rs.getString("nama_kasir") : inputNamaKasir.getText());
                    psUpdate.setString(2, inputNoTelpKasir.getText().isEmpty() ? rs.getString("no_telp") : inputNoTelpKasir.getText());
                    psUpdate.setString(3, inputAlamatKasir.getText().isEmpty() ? rs.getString("alamat") : inputAlamatKasir.getText());
                    psUpdate.setString(4, inputIdKasir.getText().toUpperCase());

                    psUpdate.executeUpdate();
                    loadDataTable();
                    JOptionPane.showMessageDialog(this,
                        "Data Kasir Dengan ID : " + inputIdKasir.getText().toUpperCase() + " Berhasil Diubah!",
                        "Sukses",
                        JOptionPane.INFORMATION_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(this,
                    "Data Kasir Dengan ID : " + inputIdKasir.getText().toUpperCase() + " Tidak Ditemukan!",
                    "Informasi",
                    JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                "Terjadi Kesalahan Saat Mengubah Data Kasir!\n" + e.getMessage(),
                "Error",
                JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }//GEN-LAST:event_ubahBtnActionPerformed

    private void hapusBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusBtnActionPerformed
        if (inputIdKasir.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this,
                "Tidak Dapat Menghapus Data. Kamu Belum Mengisi ID Kasir!",
                "Peringatan",
                JOptionPane.WARNING_MESSAGE);
            return;
        }

        String sqlCheck = "SELECT * FROM kasir WHERE id_kasir=?";
        String sqlDelete = "DELETE FROM kasir WHERE id_kasir=?";

        try (PreparedStatement psCheck = conn.prepareStatement(sqlCheck)) {
            psCheck.setString(1, inputIdKasir.getText().toUpperCase());
            ResultSet rs = psCheck.executeQuery();

            if (rs.next()) {
                try (PreparedStatement psDelete = conn.prepareStatement(sqlDelete)) {
                    psDelete.setString(1, inputIdKasir.getText().toUpperCase());
                    psDelete.executeUpdate();

                    loadDataTable();
                    JOptionPane.showMessageDialog(this,
                        "Data Kasir Dengan ID : " + inputIdKasir.getText().toUpperCase() + " Berhasil Dihapus!",
                        "Sukses",
                        JOptionPane.INFORMATION_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(this,
                    "Data Kasir Dengan ID : " + inputIdKasir.getText().toUpperCase() + " Tidak Ditemukan!",
                    "Informasi",
                    JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                "Terjadi Kesalahan Saat Menghapus Data Kasir!\n" + e.getMessage(),
                "Error",
                JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }//GEN-LAST:event_hapusBtnActionPerformed

    private void cariBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cariBtnActionPerformed
        if (inputCariKasir.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this,
                "Tidak Dapat Mencari Data. Kamu Belum Mengisi Kata Kunci!",
                "Peringatan",
                JOptionPane.WARNING_MESSAGE);
            return;
        }

        String sqlCari = "SELECT * FROM kasir WHERE id_kasir LIKE ? OR nama_kasir LIKE ?";
        try (PreparedStatement ps = conn.prepareStatement(sqlCari)) {
            String keyword = "%" + inputCariKasir.getText() + "%";
            ps.setString(1, keyword);
            ps.setString(2, keyword);

            ResultSet rs = ps.executeQuery();
            tableModel = (DefaultTableModel) table.getModel();
            tableModel.setRowCount(0);

            boolean found = false;
            while (rs.next()) {
                found = true;
                Object[] row = new Object[]{
                    rs.getString("id_kasir"),
                    rs.getString("nama_kasir"),
                    rs.getString("no_telp"),
                    rs.getString("alamat")
                };
                tableModel.addRow(row);
            }

            if (found) {
                JOptionPane.showMessageDialog(this,
                    "Data Kasir Dengan Kata Kunci : " + inputCariKasir.getText().toUpperCase() + " Berhasil Ditemukan!",
                    "Sukses",
                    JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this,
                    "Data Kasir Dengan Kata Kunci : " + inputCariKasir.getText().toUpperCase() + " Tidak Ditemukan!",
                    "Informasi",
                    JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                "Terjadi Kesalahan Saat Mencari Data Kasir!\n" + e.getMessage(),
                "Error",
                JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }//GEN-LAST:event_cariBtnActionPerformed

    private void ulangBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ulangBtnActionPerformed
        inputIdKasir.setText("");
        inputNamaKasir.setText("");
        inputNoTelpKasir.setText("");
        inputAlamatKasir.setText("");
    }//GEN-LAST:event_ulangBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cariBtn;
    private javax.swing.JButton hapusBtn;
    private javax.swing.JTextField inputAlamatKasir;
    private javax.swing.JTextField inputCariKasir;
    private javax.swing.JTextField inputIdKasir;
    private javax.swing.JTextField inputNamaKasir;
    private javax.swing.JTextField inputNoTelpKasir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton saveBtn;
    private javax.swing.JTable table;
    private javax.swing.JButton ubahBtn;
    private javax.swing.JButton ulangBtn;
    // End of variables declaration//GEN-END:variables
}
