/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package putrimarket.forn;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import putrimarket.koneksi.koneksi;

/**
 *
 * @author tobis
 */
public class Nota extends javax.swing.JPanel {
    private DefaultTableModel tableModel;
    private Connection conn = new koneksi().connect();

    /**
     * Creates new form Nota
     */
    public Nota() {
        initComponents();
        loadDataTable();
    }
    
    private void loadDataTable() {
    String sql = "SELECT * FROM nota";
    try (PreparedStatement ps = conn.prepareStatement(sql);
         ResultSet rs = ps.executeQuery()) {
        tableModel = (DefaultTableModel) table.getModel();
        tableModel.setRowCount(0);

        while (rs.next()) {
            tableModel.addRow(new Object[]{
                rs.getString("no_nota"),
                rs.getString("tanggal"),
                rs.getString("id_pelanggan"),
                rs.getString("id_kasir"),
                rs.getString("total")
            });
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this,
            "Terjadi Kesalahan Saat Memuat Data Nota!\n" + e.getMessage(),
            "Error",
            JOptionPane.ERROR_MESSAGE);
        e.printStackTrace();
    }
}

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jenisKelBtn = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        inputNoNota = new javax.swing.JTextField();
        inputIdPelanggan = new javax.swing.JTextField();
        resultNamaPelanggan = new javax.swing.JTextField();
        saveBtn = new javax.swing.JButton();
        editBtn = new javax.swing.JButton();
        hapusBtn = new javax.swing.JButton();
        ulangBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        inputCariPelanggan = new javax.swing.JTextField();
        cariBtn = new javax.swing.JButton();
        cariPelangganBtn = new javax.swing.JButton();
        inputIdKasir = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        cariKasirBtn = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        resultNamaKasir = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        inputTotal = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 153, 0));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Nota");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jLabel1)
                .addContainerGap(53, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setText("No Nota");

        jLabel5.setText("ID Pelanggan");

        jLabel6.setText("Nama Pelanggan");

        saveBtn.setText("Simpan");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        editBtn.setText("Ubah");
        editBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editBtnActionPerformed(evt);
            }
        });

        hapusBtn.setText("Hapus");
        hapusBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusBtnActionPerformed(evt);
            }
        });

        ulangBtn.setText("Ulang");
        ulangBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ulangBtnActionPerformed(evt);
            }
        });

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "No", "Tanggal", "ID Pelanggan", "ID Kasir", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(table);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Navigasi");

        jLabel8.setText("1. Tombol \"Simpan\" untuk menyimpan data");

        jLabel9.setText("2. Tombol \"Ubah\" untuk mengubah data");

        jLabel10.setText("3. Tombol \"Hapus\" untuk menghapus data");

        jLabel11.setText("4. Tombol \"Ulang\" untuk mengulang input data");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel8))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9)
                            .addComponent(jLabel11))))
                .addContainerGap(90, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        cariBtn.setText("Cari");
        cariBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cariBtnActionPerformed(evt);
            }
        });

        cariPelangganBtn.setText("Cari");
        cariPelangganBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cariPelangganBtnActionPerformed(evt);
            }
        });

        jLabel12.setText("ID Kasir");

        cariKasirBtn.setText("Cari");
        cariKasirBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cariKasirBtnActionPerformed(evt);
            }
        });

        jLabel13.setText("Nama Kasir");

        jLabel4.setText("Total");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(saveBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(editBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(hapusBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ulangBtn))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel2)
                                                .addComponent(jLabel5)
                                                .addComponent(jLabel6))
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGap(212, 212, 212)
                                                    .addComponent(cariPelangganBtn))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGap(54, 54, 54)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(inputIdPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(inputNoNota, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(resultNamaPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(inputIdKasir, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(resultNamaKasir, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(inputTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel12)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(jLabel13)
                                                .addGap(243, 243, 243)
                                                .addComponent(cariKasirBtn))))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 770, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(409, 409, 409)
                                        .addComponent(inputCariPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(cariBtn))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(321, 321, 321)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(inputNoNota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(inputIdPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cariPelangganBtn))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(resultNamaPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(inputIdKasir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cariKasirBtn))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(resultNamaKasir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(inputTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveBtn)
                    .addComponent(editBtn)
                    .addComponent(hapusBtn)
                    .addComponent(ulangBtn)
                    .addComponent(inputCariPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cariBtn))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        if (inputNoNota.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Tidak dapat menyimpan data. No Nota belum diisi!",
                    "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (inputIdPelanggan.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Tidak dapat menyimpan data. Id Pelanggan belum diisi!",
                    "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (inputIdKasir.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Tidak dapat menyimpan data. Id Kasir belum diisi!",
                    "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (inputTotal.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Tidak dapat menyimpan data. Total belum diisi!",
                    "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        String sqlCheck = "SELECT * FROM nota WHERE no_nota=?";
        String sqlInsert = "INSERT INTO nota (no_nota, id_pelanggan, id_kasir, total) VALUES (?, ?, ?, ?)";

        try (PreparedStatement psCheck = conn.prepareStatement(sqlCheck)) {
            psCheck.setString(1, inputNoNota.getText());
            ResultSet rs = psCheck.executeQuery();

            if (rs.next()) {
                JOptionPane.showMessageDialog(this,
                    "Data Nota dengan No : " + inputNoNota.getText() + " sudah terdaftar!",
                    "Informasi",
                    JOptionPane.INFORMATION_MESSAGE);
            } else {
                try (PreparedStatement psInsert = conn.prepareStatement(sqlInsert)) {
                    psInsert.setString(1, inputNoNota.getText());
                    psInsert.setString(2, inputIdPelanggan.getText());
                    psInsert.setString(3, inputIdKasir.getText());
                    psInsert.setString(4, inputTotal.getText());

                    psInsert.executeUpdate();
                    loadDataTable();
                    JOptionPane.showMessageDialog(this,
                        "Data Nota dengan No : " + inputNoNota.getText() + " berhasil disimpan!",
                        "Sukses",
                        JOptionPane.INFORMATION_MESSAGE);
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                "Terjadi Kesalahan Saat Menyimpan Data Nota!\n" + e.getMessage(),
                "Error",
                JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }

    }//GEN-LAST:event_saveBtnActionPerformed

    private void editBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBtnActionPerformed
        if (inputNoNota.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Tidak dapat mengubah data. No Nota belum diisi!",
                    "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        String sqlCheck = "SELECT * FROM nota WHERE no_nota=?";
        String sqlUpdate = "UPDATE nota SET id_pelanggan=?, id_kasir=?, total=? WHERE no_nota=?";

        try (PreparedStatement psCheck = conn.prepareStatement(sqlCheck)) {
            psCheck.setString(1, inputNoNota.getText());
            ResultSet rs = psCheck.executeQuery();

            if (rs.next()) {
                try (PreparedStatement psUpdate = conn.prepareStatement(sqlUpdate)) {
                    psUpdate.setString(1, inputIdPelanggan.getText().isEmpty() ? rs.getString("id_pelanggan") : inputIdPelanggan.getText());
                    psUpdate.setString(2, inputIdKasir.getText().isEmpty() ? rs.getString("id_kasir") : inputIdKasir.getText());
                    psUpdate.setString(3, inputTotal.getText().isEmpty() ? rs.getString("total") : inputTotal.getText());
                    psUpdate.setString(4, inputNoNota.getText());

                    psUpdate.executeUpdate();
                    loadDataTable();
                    JOptionPane.showMessageDialog(this,
                        "Data Nota dengan No : " + inputNoNota.getText() + " berhasil diubah!",
                        "Sukses",
                        JOptionPane.INFORMATION_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(this,
                    "Data Nota dengan No : " + inputNoNota.getText() + " tidak ditemukan!",
                    "Informasi",
                    JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                "Terjadi Kesalahan Saat Mengubah Data Nota!\n" + e.getMessage(),
                "Error",
                JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }//GEN-LAST:event_editBtnActionPerformed

    private void hapusBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusBtnActionPerformed
        if (inputNoNota.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Tidak dapat mengubah data. No Nota belum diisi!",
                    "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        String sqlCheck = "SELECT * FROM nota WHERE no_nota=?";
        String sqlUpdate = "UPDATE nota SET id_pelanggan=?, id_kasir=?, total=? WHERE no_nota=?";

        try (PreparedStatement psCheck = conn.prepareStatement(sqlCheck)) {
            psCheck.setString(1, inputNoNota.getText());
            ResultSet rs = psCheck.executeQuery();

            if (rs.next()) {
                try (PreparedStatement psUpdate = conn.prepareStatement(sqlUpdate)) {
                    psUpdate.setString(1, inputIdPelanggan.getText().isEmpty() ? rs.getString("id_pelanggan") : inputIdPelanggan.getText());
                    psUpdate.setString(2, inputIdKasir.getText().isEmpty() ? rs.getString("id_kasir") : inputIdKasir.getText());
                    psUpdate.setString(3, inputTotal.getText().isEmpty() ? rs.getString("total") : inputTotal.getText());
                    psUpdate.setString(4, inputNoNota.getText());

                    psUpdate.executeUpdate();
                    loadDataTable();
                    JOptionPane.showMessageDialog(this,
                        "Data Nota dengan No : " + inputNoNota.getText() + " berhasil diubah!",
                        "Sukses",
                        JOptionPane.INFORMATION_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(this,
                    "Data Nota dengan No : " + inputNoNota.getText() + " tidak ditemukan!",
                    "Informasi",
                    JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                "Terjadi Kesalahan Saat Mengubah Data Nota!\n" + e.getMessage(),
                "Error",
                JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }//GEN-LAST:event_hapusBtnActionPerformed

    private void cariBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cariBtnActionPerformed
        if (inputCariPelanggan.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this,
                "Tidak Dapat Mencari Data. Kamu Belum Mengisi Kata Kunci Pencarian!",
                "Peringatan",
                JOptionPane.WARNING_MESSAGE);
            return;
        }

        String sqlCari = "SELECT * FROM pelanggan WHERE id_pelanggan LIKE ? OR nama_pelanggan LIKE ?";
        try (PreparedStatement ps = conn.prepareStatement(sqlCari)) {
            String keyword = "%" + inputCariPelanggan.getText() + "%"; 
            ps.setString(1, keyword);
            ps.setString(2, keyword);
            ResultSet rs = ps.executeQuery();

            if (rs.next()) {
                tableModel = (DefaultTableModel) table.getModel();
                tableModel.setRowCount(0);
                do {
                    Object[] row = new Object[]{
                        rs.getString("id_pelanggan"),
                        rs.getString("nama_pelanggan"),
                        rs.getString("jenis_kelamin"),
                        rs.getString("no_telp"),
                        rs.getString("alamat")
                    };
                    tableModel.addRow(row);
                } while (rs.next());

                JOptionPane.showMessageDialog(this,
                    "Data Pelanggan Dengan Kata Kunci : " + inputCariPelanggan.getText().toUpperCase() + " Berhasil Ditemukan!",
                    "Sukses",
                    JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this,
                    "Data Pelanggan Dengan Kata Kunci : " + inputCariPelanggan.getText().toUpperCase() + " Tidak Ditemukan!",
                    "Informasi",
                    JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                "Terjadi Kesalahan Saat Mencari Data Pelanggan!\n" + e.getMessage(),
                "Error",
                JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }

    }//GEN-LAST:event_cariBtnActionPerformed

    private void ulangBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ulangBtnActionPerformed
        inputNoNota.setText("");
        inputIdPelanggan.setText("");
        inputIdKasir.setText("");
        inputTotal.setText("");
    }//GEN-LAST:event_ulangBtnActionPerformed

    private void cariPelangganBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cariPelangganBtnActionPerformed
        if (inputIdPelanggan.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this,
                "Tidak Dapat Melakukan Pencarian. Kamu Belum Mengisi ID atau Nama Pelanggan!",
                "Peringatan",
                JOptionPane.WARNING_MESSAGE);
            return;
        }

        String sql = "SELECT * FROM pelanggan WHERE id_pelanggan=? OR nama_pelanggan=?";
        try (PreparedStatement ps = conn.prepareStatement(sql)) {
            ps.setString(1, inputIdPelanggan.getText());
            ps.setString(2, inputIdPelanggan.getText());
            try (ResultSet rs = ps.executeQuery()) {
                if (rs.next()) {
                    JOptionPane.showMessageDialog(this,
                        "Data Pelanggan Dengan ID/Nama : " + inputIdPelanggan.getText().toUpperCase() + " Berhasil Ditemukan!",
                        "Sukses",
                        JOptionPane.INFORMATION_MESSAGE);
                    resultNamaPelanggan.setText(rs.getString("nama_pelanggan"));
                    resultNamaPelanggan.setEnabled(false);
                } else {
                    JOptionPane.showMessageDialog(this,
                        "Data Pelanggan Dengan ID/Nama : " + inputIdPelanggan.getText().toUpperCase() + " Tidak Ditemukan!",
                        "Informasi",
                        JOptionPane.INFORMATION_MESSAGE);
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                "Terjadi Kesalahan Saat Mencari Data Pelanggan!\n" + e.getMessage(),
                "Error",
                JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }//GEN-LAST:event_cariPelangganBtnActionPerformed

    private void cariKasirBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cariKasirBtnActionPerformed
        if (inputIdKasir.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this,
                "Tidak Dapat Melakukan Pencarian. Kamu Belum Mengisi ID atau Nama Kasir!",
                "Peringatan",
                JOptionPane.WARNING_MESSAGE);
            return;
        }

        String sql = "SELECT * FROM kasir WHERE id_kasir=? OR nama_kasir=?";
        try (PreparedStatement ps = conn.prepareStatement(sql)) {
            ps.setString(1, inputIdKasir.getText());
            ps.setString(2, inputIdKasir.getText());
            try (ResultSet rs = ps.executeQuery()) {
                if (rs.next()) {
                    JOptionPane.showMessageDialog(this,
                        "Data Kasir Dengan ID/Nama : " + inputIdKasir.getText().toUpperCase() + " Berhasil Ditemukan!",
                        "Sukses",
                        JOptionPane.INFORMATION_MESSAGE);
                    resultNamaKasir.setText(rs.getString("nama_kasir"));
                    resultNamaKasir.setEnabled(false);
                } else {
                    JOptionPane.showMessageDialog(this,
                        "Data Kasir Dengan ID/Nama : " + inputIdKasir.getText().toUpperCase() + " Tidak Ditemukan!",
                        "Informasi",
                        JOptionPane.INFORMATION_MESSAGE);
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                "Terjadi Kesalahan Saat Mencari Data Kasir!\n" + e.getMessage(),
                "Error",
                JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }//GEN-LAST:event_cariKasirBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cariBtn;
    private javax.swing.JButton cariKasirBtn;
    private javax.swing.JButton cariPelangganBtn;
    private javax.swing.JButton editBtn;
    private javax.swing.JButton hapusBtn;
    private javax.swing.JTextField inputCariPelanggan;
    private javax.swing.JTextField inputIdKasir;
    private javax.swing.JTextField inputIdPelanggan;
    private javax.swing.JTextField inputNoNota;
    private javax.swing.JTextField inputTotal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.ButtonGroup jenisKelBtn;
    private javax.swing.JTextField resultNamaKasir;
    private javax.swing.JTextField resultNamaPelanggan;
    private javax.swing.JButton saveBtn;
    private javax.swing.JTable table;
    private javax.swing.JButton ulangBtn;
    // End of variables declaration//GEN-END:variables
}
