/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package putrimarket.forn;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import putrimarket.koneksi.koneksi;

/**
 *
 * @author tobis
 */
public class Pelanggan extends javax.swing.JPanel {
    private DefaultTableModel tableModel;
    private Connection conn = new koneksi().connect();

    /**
     * Creates new form Pelanggan
     */
    public Pelanggan() {
        initComponents();
        loadDataTable();
    }
    
    private void loadDataTable() {
        tableModel = (DefaultTableModel) table.getModel();
        tableModel.setRowCount(0);

        String sql = "SELECT * FROM pelanggan";
        try (PreparedStatement ps = conn.prepareStatement(sql); 
            ResultSet rs = ps.executeQuery()) {
            while (rs.next()) {
                Object[] row = new Object[]{
                    rs.getString("id_pelanggan"),
                    rs.getString("nama_pelanggan"),
                    rs.getString("jenis_kelamin"),
                    rs.getString("no_telp"),
                    rs.getString("alamat")
                };
                tableModel.addRow(row);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    private String getJenisKelamin() {
        if (lakiRadio.isSelected()) {
            return lakiRadio.getText();
        } else if (perempuanRadio.isSelected()) {
            return perempuanRadio.getText();
        }
        return null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jenisKelBtn = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        inputIdPelanggan = new javax.swing.JTextField();
        inputNamaPelanggan = new javax.swing.JTextField();
        inputNoTelp = new javax.swing.JTextField();
        inputAlamat = new javax.swing.JTextField();
        lakiRadio = new javax.swing.JRadioButton();
        perempuanRadio = new javax.swing.JRadioButton();
        saveBtn = new javax.swing.JButton();
        editBtn = new javax.swing.JButton();
        hapusBtn = new javax.swing.JButton();
        ulangBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        inputCariPelanggan = new javax.swing.JTextField();
        cariBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 153, 0));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Pelanggan");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jLabel1)
                .addContainerGap(53, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setText("ID Pelanggan");

        jLabel3.setText("Nama Pelanggan");

        jLabel4.setText("Jenis Kelamin");

        jLabel5.setText("No Telepon");

        jLabel6.setText("Alamat");

        jenisKelBtn.add(lakiRadio);
        lakiRadio.setText("Laki-laki");

        jenisKelBtn.add(perempuanRadio);
        perempuanRadio.setText("Perempuan");

        saveBtn.setText("Simpan");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        editBtn.setText("Ubah");
        editBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editBtnActionPerformed(evt);
            }
        });

        hapusBtn.setText("Hapus");
        hapusBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusBtnActionPerformed(evt);
            }
        });

        ulangBtn.setText("Ulang");
        ulangBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ulangBtnActionPerformed(evt);
            }
        });

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Nama", "Jenis Kelamin", "No Telp", "Alamat"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(table);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Navigasi");

        jLabel8.setText("1. Tombol \"Simpan\" untuk menyimpan data");

        jLabel9.setText("2. Tombol \"Ubah\" untuk mengubah data");

        jLabel10.setText("3. Tombol \"Hapus\" untuk menghapus data");

        jLabel11.setText("4. Tombol \"Ulang\" untuk mengulang input data");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel8))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9)
                            .addComponent(jLabel11))))
                .addContainerGap(90, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        cariBtn.setText("Cari");
        cariBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cariBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 770, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel6))
                                    .addGap(59, 59, 59)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(lakiRadio)
                                            .addGap(18, 18, 18)
                                            .addComponent(perempuanRadio))
                                        .addComponent(inputIdPelanggan, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
                                        .addComponent(inputNamaPelanggan)
                                        .addComponent(inputNoTelp)
                                        .addComponent(inputAlamat))
                                    .addGap(37, 37, 37)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(inputCariPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(cariBtn))
                                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(saveBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(editBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(hapusBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ulangBtn))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(321, 321, 321)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(inputIdPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(inputNamaPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(lakiRadio)
                            .addComponent(perempuanRadio))
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(inputNoTelp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(inputAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveBtn)
                    .addComponent(editBtn)
                    .addComponent(hapusBtn)
                    .addComponent(ulangBtn)
                    .addComponent(inputCariPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cariBtn))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        if (inputIdPelanggan.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this,
                "Tidak Dapat Menyimpan Data. Kamu Belum Mengisi ID Pelanggan!",
                "Peringatan",
                JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (inputNamaPelanggan.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this,
                "Tidak Dapat Menyimpan Data. Kamu Belum Mengisi Nama Pelanggan!",
                "Peringatan",
                JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (getJenisKelamin().isEmpty()) {
            JOptionPane.showMessageDialog(this,
                "Tidak Dapat Menyimpan Data. Kamu Belum Memilih Jenis Kelamin!",
                "Peringatan",
                JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (inputNoTelp.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this,
                "Tidak Dapat Menyimpan Data. Kamu Belum Mengisi Nomor Telepon!",
                "Peringatan",
                JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (inputAlamat.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this,
                "Tidak Dapat Menyimpan Data. Kamu Belum Mengisi Alamat!",
                "Peringatan",
                JOptionPane.WARNING_MESSAGE);
            return;
        }

        String sqlCheck = "SELECT * FROM pelanggan WHERE id_pelanggan=?";
        String sqlInsert = "INSERT INTO pelanggan (id_pelanggan, nama_pelanggan, jenis_kelamin, no_telp, alamat) VALUES (?, ?, ?, ?, ?)";

        try (PreparedStatement psCheck = conn.prepareStatement(sqlCheck)) {
            psCheck.setString(1, inputIdPelanggan.getText().toUpperCase());
            ResultSet rs = psCheck.executeQuery();

            if (rs.next()) {
                JOptionPane.showMessageDialog(this,
                        "Data Barang Dengan ID : " + inputIdPelanggan.getText().toUpperCase() + " Sudah Terdaftar!",
                        "Informasi",
                        JOptionPane.INFORMATION_MESSAGE);
            } else {
                try (PreparedStatement psInsert = conn.prepareStatement(sqlInsert)) {
                    psInsert.setString(1, inputIdPelanggan.getText().toUpperCase());
                    psInsert.setString(2, inputNamaPelanggan.getText());
                    psInsert.setString(3, getJenisKelamin());
                    psInsert.setString(4, inputNoTelp.getText());
                    psInsert.setString(5, inputAlamat.getText());

                    psInsert.executeUpdate();
                    loadDataTable();
                    JOptionPane.showMessageDialog(this,
                        "Data Barang Dengan ID : " + inputIdPelanggan.getText().toUpperCase() + " Berhasil Disimpan!",
                        "Sukses",
                        JOptionPane.INFORMATION_MESSAGE);
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                "Terjadi Kesalahan Saat Menyimpan Data Pelanggan!\n" + e.getMessage(),
                "Error",
                JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }//GEN-LAST:event_saveBtnActionPerformed

    private void editBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBtnActionPerformed
        if (inputIdPelanggan.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this,
                "Tidak Dapat Menyimpan Data. Kamu Belum Mengisi ID Pelanggan!",
                "Peringatan",
                JOptionPane.WARNING_MESSAGE);
            return;
        }

        String sqlCheck = "SELECT * FROM pelanggan WHERE id_pelanggan=?";
        try (PreparedStatement psCheck = conn.prepareStatement(sqlCheck)) {

            psCheck.setString(1, inputIdPelanggan.getText());
            ResultSet rs = psCheck.executeQuery();

            if (rs.next()) {
                String sqlUpdate = "UPDATE pelanggan SET nama_pelanggan=?, jenis_kelamin=?, no_telp=?, alamat=? WHERE id_pelanggan=?";
                try (PreparedStatement psUpdate = conn.prepareStatement(sqlUpdate)) {
                    psUpdate.setString(1, inputNamaPelanggan.getText().isEmpty() 
                            ? rs.getString("nama_pelanggan") 
                            : inputNamaPelanggan.getText());
                    psUpdate.setString(2, getJenisKelamin().isEmpty() 
                            ? rs.getString("jenis_kelamin") 
                            : getJenisKelamin());
                    psUpdate.setString(3, inputNoTelp.getText().isEmpty() 
                            ? rs.getString("no_telp") 
                            : inputNoTelp.getText());
                    psUpdate.setString(4, inputAlamat.getText().isEmpty() 
                            ? rs.getString("alamat") 
                            : inputAlamat.getText());
                    psUpdate.setString(5, inputIdPelanggan.getText());

                    psUpdate.executeUpdate();
                    loadDataTable();
                    JOptionPane.showMessageDialog(this,
                        "Data Pelanggan Dengan ID : " + inputIdPelanggan.getText().toUpperCase() + " Berhasil Diubah!",
                        "Sukses",
                        JOptionPane.INFORMATION_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(this,
                        "Data Pelanggan Dengan ID : " + inputIdPelanggan.getText().toUpperCase() + " Tidak Terdaftar!",
                        "Informasi",
                        JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "Terjadi Kesalahan Saat Mengubah Data Pelanggan!\n" + e.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }//GEN-LAST:event_editBtnActionPerformed

    private void hapusBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusBtnActionPerformed
        if (inputIdPelanggan.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this,
                "Tidak Dapat Menghapus Data. Kamu Belum Mengisi ID Pelanggan!",
                "Peringatan",
                JOptionPane.WARNING_MESSAGE);
            return;
        }

        String sqlCheck = "SELECT * FROM pelanggan WHERE id_pelanggan=?";
        try (PreparedStatement psCheck = conn.prepareStatement(sqlCheck)) {
            psCheck.setString(1, inputIdPelanggan.getText());
            ResultSet rs = psCheck.executeQuery();

            if (rs.next()) {
                String sqlDelete = "DELETE FROM pelanggan WHERE id_pelanggan=?";
                PreparedStatement psDelete = conn.prepareStatement(sqlDelete);
                psDelete.setString(1, inputIdPelanggan.getText().toUpperCase());
                psDelete.executeUpdate();

                loadDataTable();
                JOptionPane.showMessageDialog(this,
                        "Data Pelanggan Dengan ID : " + inputIdPelanggan.getText().toUpperCase() + " Berhasil Dihapus!",
                        "Sukses",
                        JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this,
                    "Data Pelanggan Dengan ID : " + inputIdPelanggan.getText().toUpperCase() + " Tidak Ditemukan!",
                    "Informasi",
                    JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                "Terjadi Kesalahan Saat Menghapus Data Pelanggan!\n" + e.getMessage(),
                "Error",
                JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }//GEN-LAST:event_hapusBtnActionPerformed

    private void cariBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cariBtnActionPerformed
        if (inputCariPelanggan.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this,
                "Tidak Dapat Mencari Data. Kamu Belum Mengisi Kata Kunci Pencarian!",
                "Peringatan",
                JOptionPane.WARNING_MESSAGE);
            return;
        }

        String sqlCari = "SELECT * FROM pelanggan WHERE id_pelanggan LIKE ? OR nama_pelanggan LIKE ?";
        try (PreparedStatement ps = conn.prepareStatement(sqlCari)) {
            String keyword = "%" + inputCariPelanggan.getText() + "%"; 
            ps.setString(1, keyword);
            ps.setString(2, keyword);
            ResultSet rs = ps.executeQuery();

            if (rs.next()) {
                tableModel = (DefaultTableModel) table.getModel();
                tableModel.setRowCount(0);
                do {
                    Object[] row = new Object[]{
                        rs.getString("id_pelanggan"),
                        rs.getString("nama_pelanggan"),
                        rs.getString("jenis_kelamin"),
                        rs.getString("no_telp"),
                        rs.getString("alamat")
                    };
                    tableModel.addRow(row);
                } while (rs.next());

                JOptionPane.showMessageDialog(this,
                    "Data Pelanggan Dengan Kata Kunci : " + inputCariPelanggan.getText().toUpperCase() + " Berhasil Ditemukan!",
                    "Sukses",
                    JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this,
                    "Data Pelanggan Dengan Kata Kunci : " + inputCariPelanggan.getText().toUpperCase() + " Tidak Ditemukan!",
                    "Informasi",
                    JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                "Terjadi Kesalahan Saat Mencari Data Pelanggan!\n" + e.getMessage(),
                "Error",
                JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }

    }//GEN-LAST:event_cariBtnActionPerformed

    private void ulangBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ulangBtnActionPerformed
        inputIdPelanggan.setText("");
        inputNamaPelanggan.setText("");
        inputNoTelp.setText("");
        inputAlamat.setText("");
        jenisKelBtn.clearSelection(); 
    }//GEN-LAST:event_ulangBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cariBtn;
    private javax.swing.JButton editBtn;
    private javax.swing.JButton hapusBtn;
    private javax.swing.JTextField inputAlamat;
    private javax.swing.JTextField inputCariPelanggan;
    private javax.swing.JTextField inputIdPelanggan;
    private javax.swing.JTextField inputNamaPelanggan;
    private javax.swing.JTextField inputNoTelp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.ButtonGroup jenisKelBtn;
    private javax.swing.JRadioButton lakiRadio;
    private javax.swing.JRadioButton perempuanRadio;
    private javax.swing.JButton saveBtn;
    private javax.swing.JTable table;
    private javax.swing.JButton ulangBtn;
    // End of variables declaration//GEN-END:variables
}
